DROP SCHEMA IF EXISTS advising_admin;

CREATE DATABASE `advising_admin` /*!40100 DEFAULT CHARACTER SET latin1 */;

DROP SCHEMA IF EXISTS advising;

CREATE DATABASE `advising` /*!40100 DEFAULT CHARACTER SET latin1 */;


